#!/usr/bin/with-contenv bash

while inotifywait -s -q -r /config -e modify -e move -e create -e delete; do
    # Sleep a couple seconds in case more than one file is updated
    sleep 5
    # Reload named
    rndc reload
done
