#!/usr/bin/with-contenv bash

while inotifywait -s -q -r /config -e attrib,modify,move,create,delete; do
    # Sleep a couple seconds in case more than one file is updated
    sleep 5
    # Reload named
    rndc reload
done
